// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgffumg4_QSzdWlShISLmTNE1ThHJ9LtE',
    appId: '1:668788421060:web:c8105ead835b698ffd3491',
    messagingSenderId: '668788421060',
    projectId: 'todo-app-e7672',
    authDomain: 'todo-app-e7672.firebaseapp.com',
    storageBucket: 'todo-app-e7672.firebasestorage.app',
    measurementId: 'G-DCLB2JK6EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF7ctuRqogKs9Jx_1m0lkHUtxcImeKC3s',
    appId: '1:668788421060:android:a5e0407e4ed636e4fd3491',
    messagingSenderId: '668788421060',
    projectId: 'todo-app-e7672',
    storageBucket: 'todo-app-e7672.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3MMgr-kTfsezscCkd4EdRWJ_7lkFxkig',
    appId: '1:668788421060:ios:ccbbc2b0fabd8011fd3491',
    messagingSenderId: '668788421060',
    projectId: 'todo-app-e7672',
    storageBucket: 'todo-app-e7672.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3MMgr-kTfsezscCkd4EdRWJ_7lkFxkig',
    appId: '1:668788421060:ios:ccbbc2b0fabd8011fd3491',
    messagingSenderId: '668788421060',
    projectId: 'todo-app-e7672',
    storageBucket: 'todo-app-e7672.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgffumg4_QSzdWlShISLmTNE1ThHJ9LtE',
    appId: '1:668788421060:web:fb708057758e92b0fd3491',
    messagingSenderId: '668788421060',
    projectId: 'todo-app-e7672',
    authDomain: 'todo-app-e7672.firebaseapp.com',
    storageBucket: 'todo-app-e7672.firebasestorage.app',
    measurementId: 'G-8QZWB5HGQ4',
  );
}
